BUG: Update scene parameter to be non-optional in data unit initializers
 # Scene is NOT optional.
# Raises `AttributeError: 'NoneType' object has no attribute 'GetSubjectHierarchyNode'
# Default scene is the global MRML scene, which is always available.